### ISSUE TITLE
화면 수정안 

### ISSUE THREAD

**Issue by 1argeD** [TAE-Trial-and-error/mit305#61]
### 토탈페이지
접근이 용이하게 토탈페이지 구현할 것

### 로그인 기능 추가
추후 

### 물품등록
1.품목이 계약 여부 확인이 가능하게 구정되어야함
2. 품목 리스트 구분해서 구현하기

### 조달계획등록
1.날짜로 리스트를 불러와서 등록
2.발주상태를 보여줄 필요가 없음 수정해야함
3.한 달 간격으로 품목을 찾을 수 있게 날짜 검색 기능 추가 하기
4.발주서가 나온 시점에는 계획 등록에 수정 버튼 비활성화

### 계약서 목록
1.계약 품목 추가 버튼 삭제
2.품목명 품목 코드 테이블 위치 변경
3.계약 목록 리스트 따로 만들어서 보여주기
4.계약 리스트 별로 이메일 전송 버튼, 계약 수정 버튼 추가하기

### 발주서 등록 전 발주 품목 선택창 구현하기
1.발주서를 만들때 넣어줄 발주 품목을 선택할 페이지을 구현해야함
 
### 발주서 등록
1.업체 선택명이 해당 페이지에서 검색 기능을 하고 있지만, 위치가 아래에 있어 기능에 오해를 줄 수 있기 때문에 맨 위로 올리도록 수정함.

### 발주서 목록
1.검수 여부 칼럼 삭제
2.발주 상태 칼럼을 진척검수 등록으로 변경(버튼으로)
3.검수 완료 되면 등록버튼 표시되지 않게

### 진척 검수 등록 
1.진척 검수 칼럼을 등록 버튼으로 변경
단, 진척 검수 등록이 완료되면 등록 버튼은 수정으로 변경하고 진척 검수 일정을 수정할 수 있도록 구현한다 .
기존의 진척 일정 페이지에서 [미검수] 대신 진적 첨수 일정에 따라서 품목 수준 평가를 할 수 있는 버튼을 구현하고, 
진척 검수  품목 수준 평가가 완료하면 더 이상 해당 품목에 대한 진척 검수 일정을 등록, 수정, 삭제 할 수 없게 모든 버튼을 막는다. 

2.(+) 를 누르면 진척 검수를 등록하던 방식(기존) => 등록창을 기본으로 하나 띄워주고 진척 검수를 등록하면 아래에 등록창이 생성되는 방식으로 등으로 변경 

### 발주 현황관리
1.기준을 발주서 명에서 품목 기준으로 변경

### 재고관리
1.재고 품목을 입고 처리된 전체 품목이 아니라 조달 계획에서 받아와서 해당 품목만 수정하도록 구현
2. 재고 더 많은 정보 제공해야함

### 재고 현환관리
1.분류별 재고 금액을 보여주는 등 다른 추가적인 그래프나 리포트를 보여주도록 구현할 것

**Comment by acbine** [comment]
조달 계획을 등록하고 나서 발주서를  발행하기전에 품목에 대한 상태값이 있어야 발주 현황관리 중에서 [*발주서 미발행* , 발주서 발행 , 발주서검수진행중 , 검수처리완료 , 입고마감=발주서 마감] 등을 표시 할 수 있습니다

**Comment by 1argeD** [comment]
기존조달계획 테이블에 OrderState 값이 있으니 발주 전, 발주 후, 진척검수 마다 상태를 변화시키고 그 값을 불러와서 사용하면 될거 같습니다.

**Comment by 1argeD** [comment]
입고처리 부분도 발주서가 아니라 품목별로 처리해야 될 거 같습니다
